"""reality_compiler/template_library.py — BehaviorTemplate registry.

Each template has:
  name         — matches BehaviorIntent.type
  lua_template — string.Template Lua code (${variable} substitution)
  host_template— string.Template Python host-glue code
  test_spec    — dict describing emulator injection + assertions
"""
from __future__ import annotations

from dataclasses import dataclass, field
from string import Template
from typing import Any


@dataclass
class BehaviorTemplate:
    name: str
    lua_template: str
    host_template: str
    test_spec: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Template registry
# ---------------------------------------------------------------------------

_REGISTRY: dict[str, BehaviorTemplate] = {}


def register(t: BehaviorTemplate) -> BehaviorTemplate:
    _REGISTRY[t.name] = t
    return t


def get(name: str) -> BehaviorTemplate:
    if name not in _REGISTRY:
        raise KeyError(f"No template registered for behavior: {name!r}")
    return _REGISTRY[name]


def list_behaviors() -> list[str]:
    return sorted(_REGISTRY.keys())


# ---------------------------------------------------------------------------
# Shared host template (used by all behaviors)
# ---------------------------------------------------------------------------

_HOST_TEMPLATE = '''\
import asyncio
from brilliant_msg import BrilliantMsg  # pip install memoscape[hardware]

async def main():
    d = BrilliantMsg()
    await d.connect()
    await d.upload_stdlua_libs(["data", "plain_text"])
    await d.upload_frame_app("lua/main.lua")
    d.attach_print_response_handler()
    await d.start_frame_app()
    ${host_extra}
    await asyncio.sleep(${run_sec})
    await d.stop_frame_app()
    await d.disconnect()

if __name__ == "__main__":
    asyncio.run(main())
'''

# ---------------------------------------------------------------------------
# round_timer
# ---------------------------------------------------------------------------

register(BehaviorTemplate(
    name="round_timer",
    lua_template='''\
-- round_timer.lua  (generated by Reality Compiler)
local data = require("data.min")

local DURATION     = ${duration_sec}
local OVERTIME     = ${overtime_sec}
local WARN_AT      = ${warning_start_sec}
local WARN_COLOR   = "${warning_color}"
local running      = false
local t_remaining  = DURATION

local function show_time(secs, label)
    frame.display.text(label or "", 10, 40)
    frame.display.text(tostring(secs), 10, 80)
    frame.display.show()
end

local function run_timer(total, label)
    local remaining = total
    while running and remaining > 0 do
        local color = (remaining <= WARN_AT) and WARN_COLOR or "WHITE"
        show_time(remaining, label)
        frame.sleep(1.0)
        remaining = remaining - 1
    end
    return remaining
end

frame.button.${trigger}(function()
    if running then
        running = false
        frame.display.text("STOPPED", 10, 80)
        frame.display.show()
        return
    end
    running = true
    frame.display.text("ROUND", 10, 40)
    frame.display.show()
    run_timer(DURATION, "ROUND")
    if running and OVERTIME > 0 then
        run_timer(OVERTIME, "OT")
    end
    running = false
    frame.display.text("OVER", 10, 80)
    frame.display.show()
end)

frame.display.text("Double-tap: start", 10, 80)
frame.display.show()

while true do
    frame.sleep(0.5)
end
''',
    host_template=_HOST_TEMPLATE,
    test_spec={
        "inject": "double_click",
        "wait_ms": 500,
        "assert_bright": True,
    },
))

# ---------------------------------------------------------------------------
# stopwatch
# ---------------------------------------------------------------------------

register(BehaviorTemplate(
    name="stopwatch",
    lua_template='''\
-- stopwatch.lua  (generated by Reality Compiler)
local running   = false
local start_t   = 0
local elapsed   = 0

local function fmt(secs)
    local m = math.floor(secs / 60)
    local s = secs % 60
    return string.format("%02d:%02d", m, s)
end

frame.button.${trigger_start}(function()
    if running then
        elapsed = os.clock() - start_t
        running = false
        frame.display.text("STOPPED", 10, 40)
        frame.display.text(fmt(math.floor(elapsed)), 10, 80)
    else
        start_t = os.clock()
        running  = true
        frame.display.text("RUNNING", 10, 40)
    end
    frame.display.show()
end)

frame.button.${trigger_reset}(function()
    running  = false
    elapsed  = 0
    frame.display.text("RESET", 10, 80)
    frame.display.show()
end)

frame.display.text("Tap: start/stop", 10, 80)
frame.display.show()

while true do
    if running then
        local t = os.clock() - start_t
        frame.display.text(fmt(math.floor(t)), 10, 80)
        frame.display.show()
    end
    frame.sleep(0.25)
end
''',
    host_template=_HOST_TEMPLATE,
    test_spec={"inject": "single_click", "wait_ms": 300, "assert_bright": True},
))

# ---------------------------------------------------------------------------
# interval_timer
# ---------------------------------------------------------------------------

register(BehaviorTemplate(
    name="interval_timer",
    lua_template='''\
-- interval_timer.lua  (generated by Reality Compiler)
local WORK_SEC  = ${work_sec}
local REST_SEC  = ${rest_sec}
local ROUNDS    = ${rounds}
local running   = false
local cur_round = 0

frame.button.${trigger}(function()
    if running then running = false; return end
    running   = true
    cur_round = 0
    while running and cur_round < ROUNDS do
        cur_round = cur_round + 1
        frame.display.text("WORK " .. cur_round .. "/" .. ROUNDS, 10, 40)
        frame.display.show()
        for i = WORK_SEC, 1, -1 do
            if not running then break end
            frame.display.text(tostring(i), 10, 80)
            frame.display.show()
            frame.sleep(1.0)
        end
        if REST_SEC > 0 and running then
            frame.display.text("REST", 10, 40)
            frame.display.show()
            for i = REST_SEC, 1, -1 do
                if not running then break end
                frame.display.text(tostring(i), 10, 80)
                frame.display.show()
                frame.sleep(1.0)
            end
        end
    end
    running = false
    frame.display.text("DONE!", 10, 80)
    frame.display.show()
end)

frame.display.text("Tap: start intervals", 10, 80)
frame.display.show()

while true do frame.sleep(0.5) end
''',
    host_template=_HOST_TEMPLATE,
    test_spec={"inject": "double_click", "wait_ms": 300, "assert_bright": True},
))

# ---------------------------------------------------------------------------
# simple_counter
# ---------------------------------------------------------------------------

register(BehaviorTemplate(
    name="simple_counter",
    lua_template='''\
-- simple_counter.lua  (generated by Reality Compiler)
local count = ${start_value}
local INC   = ${increment}

local function show()
    frame.display.text("COUNT", 10, 40)
    frame.display.text(tostring(count), 10, 80)
    frame.display.show()
end

frame.button.${trigger}(function()
    count = count + INC
    show()
end)

frame.button.${reset_trigger}(function()
    count = ${start_value}
    show()
end)

show()
while true do frame.sleep(0.5) end
''',
    host_template=_HOST_TEMPLATE,
    test_spec={"inject": "single_click", "wait_ms": 200, "assert_bright": True},
))

# ---------------------------------------------------------------------------
# battery_warning
# ---------------------------------------------------------------------------

register(BehaviorTemplate(
    name="battery_warning",
    lua_template='''\
-- battery_warning.lua  (generated by Reality Compiler)
local THRESHOLD  = ${threshold_pct}
local INTERVAL   = ${check_interval_sec}
local WARN_COLOR = "${warning_color}"

local function check()
    local level = frame.battery_level()
    if level ~= nil and level < THRESHOLD then
        frame.display.text("LOW BATTERY", 10, 40)
        frame.display.text(tostring(level) .. "%", 10, 80)
        frame.display.show()
        frame.sleep(3.0)
        frame.display.clear()
        frame.display.show()
    end
end

while true do
    check()
    frame.sleep(INTERVAL)
end
''',
    host_template=_HOST_TEMPLATE,
    test_spec={"inject": None, "wait_ms": 200, "assert_bright": False},
))

# ---------------------------------------------------------------------------
# teleprompter
# ---------------------------------------------------------------------------

register(BehaviorTemplate(
    name="teleprompter",
    lua_template='''\
-- teleprompter.lua  (generated by Reality Compiler)
local SCROLL_SPEED = ${scroll_speed}
local TILT_CONTROL = ${tilt_control}
local lines        = {"Your text here"}  -- host sends lines via BLE
local offset       = 0
local LINE_H       = 18

local function render()
    frame.display.clear()
    for i, line in ipairs(lines) do
        local y = (i - 1) * LINE_H - offset
        if y > -LINE_H and y < 256 then
            frame.display.text(line, 10, y)
        end
    end
    frame.display.show()
end

while true do
    local speed = SCROLL_SPEED
    if TILT_CONTROL then
        local imu = frame.imu_data()
        if imu and imu.pitch then
            speed = SCROLL_SPEED * (1 + imu.pitch * 2)
        end
    end
    offset = offset + speed
    render()
    frame.sleep(0.1)
end
''',
    host_template=_HOST_TEMPLATE,
    test_spec={"inject": None, "wait_ms": 300, "assert_bright": True},
))

# ---------------------------------------------------------------------------
# coaching_cue
# ---------------------------------------------------------------------------

register(BehaviorTemplate(
    name="coaching_cue",
    lua_template='''\
-- coaching_cue.lua  (generated by Reality Compiler)
local CUE_MAP = {
    [1] = "ATTACK",
    [2] = "DEFEND",
    [3] = "RESET",
    [4] = "TIME",
}
local DISPLAY_MS = ${display_duration_ms}

function on_data(data)
    local code = string.byte(data, 1)
    local label = CUE_MAP[code] or "CUE " .. tostring(code)
    frame.display.text(label, 10, 80)
    frame.display.show()
    frame.sleep(DISPLAY_MS / 1000.0)
    frame.display.clear()
    frame.display.show()
end

frame.bluetooth.receive_callback(on_data)

frame.display.text("Coach cue ready", 10, 80)
frame.display.show()

while true do frame.sleep(0.5) end
''',
    host_template=_HOST_TEMPLATE,
    test_spec={
        "inject": "bluetooth",
        "bluetooth_data": b"\x01",
        "wait_ms": 300,
        "assert_bright": True,
    },
))

# ---------------------------------------------------------------------------
# points_marker
# ---------------------------------------------------------------------------

register(BehaviorTemplate(
    name="points_marker",
    lua_template='''\
-- points_marker.lua  (generated by Reality Compiler)
local points = 0

local function show()
    frame.display.text("POINTS", 10, 40)
    frame.display.text(tostring(points), 10, 80)
    frame.display.show()
end

frame.button.${trigger}(function()
    points = points + 1
    show()
    ${send_expr}
end)

frame.button.${undo_trigger}(function()
    if points > 0 then
        points = points - 1
        show()
    end
end)

show()
while true do frame.sleep(0.5) end
''',
    host_template=_HOST_TEMPLATE,
    test_spec={"inject": "single_click", "wait_ms": 200, "assert_bright": True},
))

# ---------------------------------------------------------------------------
# habit_reminder
# ---------------------------------------------------------------------------

register(BehaviorTemplate(
    name="habit_reminder",
    lua_template='''\
-- habit_reminder.lua  (generated by Reality Compiler)
local INTERVAL_SEC = ${interval_min} * 60
local TEXT         = "${reminder_text}"
local DISPLAY_SEC  = ${display_duration_sec}

while true do
    frame.sleep(INTERVAL_SEC)
    frame.display.text(TEXT, 10, 80)
    frame.display.show()
    frame.sleep(DISPLAY_SEC)
    frame.display.clear()
    frame.display.show()
end
''',
    host_template=_HOST_TEMPLATE,
    test_spec={"inject": None, "wait_ms": 200, "assert_bright": False},
))

# ---------------------------------------------------------------------------
# react_timer
# ---------------------------------------------------------------------------

register(BehaviorTemplate(
    name="react_timer",
    lua_template='''\
-- react_timer.lua  (generated by Reality Compiler)
local MIN_MS   = ${min_delay_ms}
local MAX_MS   = ${max_delay_ms}
local waiting  = false
local flash_t  = 0

math.randomseed(os.clock())

local function next_round()
    frame.display.text("Get ready...", 10, 80)
    frame.display.show()
    local delay = MIN_MS + math.random(MAX_MS - MIN_MS)
    frame.sleep(delay / 1000.0)
    flash_t   = os.clock()
    waiting   = true
    frame.display.text("GO!", 10, 80)
    frame.display.show()
end

frame.button.${trigger}(function()
    if waiting then
        local reaction_ms = math.floor((os.clock() - flash_t) * 1000)
        waiting = false
        frame.display.text(tostring(reaction_ms) .. " ms", 10, 80)
        frame.display.show()
        frame.sleep(2.0)
        next_round()
    else
        next_round()
    end
end)

frame.display.text("Tap to start", 10, 80)
frame.display.show()
while true do frame.sleep(0.1) end
''',
    host_template=_HOST_TEMPLATE,
    test_spec={"inject": "single_click", "wait_ms": 300, "assert_bright": True},
))
